<div style="width:100%; background-color:#181818; color:#f1f1f1; padding:30px 0; text-align:center; border-radius:10px;">
  <img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmhqeWs3OTFqMmpsdnF2ejdjZmprZmFoNHlscHRldm1zNzhrZGF2bCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l1KdbHUPe27GQsJH2/giphy.gif" alt="Reinforced concrete design animation" width="700" style="max-width:100%; border-radius:10px;">
  <h3 style="color:#ffffff; margin:15px 0 8px 0;"><b>Introduction to Reinforced Concrete Design II</b></h3>
  <p style="margin:4px 0;"><b>Authors:</b> Msc. Ing. Carlos Andrés Celi Sánchez · Nicolás Mora Bowen · Juan Sebastián Baquero</p>
  <p style="margin:4px 0;"><b>Course:</b> Reinforced Concrete Design II</p>
  <p style="margin:4px 0; color:#d1d5db;">Basic Coding.</p>
</div>

### Libraries

In [58]:
import numpy as np
import pandas as pd

### Basic Operations

#### Aritmetic

In [59]:
a = np.sum(2+3)
a_df = pd.DataFrame([a], columns=['value'])
print('=' * 80)
print(f'The value of a = {a}')
print('=' * 80)

================================================================================
The value of a = 5
================================================================================

In [60]:
a_df

   value
0      5

#### Basic Arrays

In [61]:
b = np.array([1,2,3,4,5])
c = np.array(
    [[1,6],
     [2,7],
     [3,8],
     [4,9],
     [5,10]
    ]
)

b_df = pd.DataFrame(b, columns=['values'])
c_df = pd.DataFrame(c, columns=['value 1', 'value2'])

print('=' * 80)
print(f'The value of the array b = {b}')
print(f'The value of the array c = {c}')
print('=' * 80)

c_df.head(len(c_df))

================================================================================
The value of the array b = [1 2 3 4 5]
The value of the array c = [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
================================================================================

   value 1  value2
0        1       6
1        2       7
2        3       8
3        4       9
4        5      10